### ISSUE TITLE
Observing a NetworkConnection StateFlow on iOS Simulator doesn't work

### ISSUE THREAD

**Issue by stevdza-san** [plusmobileapps/konnectivity#3]
This is my sample code. On Android it works fine, however on iOS simulator, it doesn't trigger automatically when I disable an internet connection on my Macbook. Not sure if it's related to the simulator itself and not being able to turn off a connection from the settings? I do not own an iPhone yet, so I can't test it there, even though I'm sure on a real device it would work! 

Thanks for this handy library btw! :)

```kotlin
@Composable
@Preview
fun App() {
    MaterialTheme {
        val konnectivity by remember { mutableStateOf(Konnectivity()) }
        val status by konnectivity.currentNetworkConnectionState.collectAsState()
        val isConnected by konnectivity.isConnectedState.collectAsState()

        Column (
            modifier = Modifier.fillMaxSize(),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center
        ) {
            Text(
                text = status.name,
                fontSize = MaterialTheme.typography.displaySmall.fontSize
            )
            Spacer(modifier = Modifier.height(12.dp))
            Text(
                text = isConnected.toString(),
                fontSize = MaterialTheme.typography.titleLarge.fontSize
            )
        }
    }
}
```

**Comment by vengateshm** [comment]
Nice library.

**Comment by plusmobileapps** [comment]
Unfortunately this is a limitation with iOS simulator. I can update the documentation about this but it should work on a physical device from my own testing. Don't know why apple doesn't improve the iOS simulator experience because there's not even an airplane mode available to toggle the network like android and you have to turn off the entire network on your computer.
